# Generated by Django 5.2.17 on 2026-08-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('group_size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('image_url', models.URLField(max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
